### ISSUE TITLE
[ TASK ] Presale Marketing Material

### ISSUE THREAD

**Issue by frasercarter** [gracie-platform/control-deck#15]
**Summary:** Tracks the development of marketing material for the presale campaign.

**Dependents:** 
**Observers:** @frasercarter, @britt-w 

**Detail:**
We need to create some material for use in the presale campaign, this includes

**Sub-Tasks:**
- [ ] Twitter Images 
- [ ] Content for the presale page
- [ ] Content for the website to clearly describe the product.
- [ ] We may need to formalize a Revenue Model and some Tokenomics.
