### ISSUE TITLE
[ TASK ] Apply to Web3 Accelerators

### ISSUE THREAD

**Issue by 65156** [gracie-platform/control-deck#2]
**Summary:** to track our applications to various web3 accelerators.

**Dependents:** n/a
**Observers:** @onigiri-x,

**Detail:**

Complete
- [x] Variant.fund //rejected
- [x] https://fellowship.orangedao.xyz/ 
- [x] https://www.seedclub.xyz/
- [x] https://www.longhash.vc/
- [x] https://outlierventures.io/general-base-camp/
- [x] https://www.mousebelt.com/accelerator
- [x] https://alliance.xyz/
- [x] https://www.theblox.co/ 
- [x] https://www.web3native.co/programs/kraken-grants
- [x] https://www.web3native.co/programs/decentraland-grants-higher-tier
- [x] https://csl.chainhub.foundation/ //rejected

Pending
- [ ] https://www.gravitonaccelerator.com/
- [ ] https://stacks.ac/#funding

Binned (for now)
- [ ] https://www.brinc.io/blockchain/ , waiting for next cohort
- [ ] https://a16zcrypto.com/crypto-startup-school/, **
- [ ] https://fractalweb3.com/, **
- [ ] https://www.techstars.com/accelerators/web3, **
- [ ] https://www.0xbeacon.com/apply, **
- [ ] https://developer.mastercard.com/programs/start-path-crypto/, later stage accelerator
- [ ] https://cointelegraph.com/accelerate/, This is a later stage accelerator.
- [ ] https://delphilabs.io/accelerator-details#apply, cosmos only

**Sub-Tasks:**
- [x] #3
- [ ] #4

**Questions**
1. Please provide a comprehensive overview of your academic and professional background. Share relevant information about your experience, including any companies you have founded and/or notable academic achievements. Be sure to focus on those outcomes that demonstrate your capabilities. We ask that you maintain a professional tone and keep your response concise. (1-2 paragraphs)*

 2. Tell us, what skillset do you bring to the team? (1-2 paragraphs)*

 3. Include any other links to your work here. Previous companies, Substack, portfolios etc.
