### ISSUE TITLE
[ TASK ] Configure Development Pipelines into Google Cloud

### ISSUE THREAD

**Issue by 65156** [gracie-platform/control-deck#5]
**Summary:** We will sett up some development pipelines into GCP.

**Dependents:** Outline task or issue dependencies here. 
**Observers:** @frasercarter 

**Detail:**
Setup of Dev and Production Pipelines

**Sub-Tasks:**
- [ ] Create Github Organizational Secret Key
- [ ] configure Github Actions 
- [ ] Terraform for declarative infrastructure.
