### ISSUE TITLE
[ TASK ] Contact Key Members of WHR

### ISSUE THREAD

**Issue by 65156** [gracie-platform/control-deck#8]
**Summary:** Contact Members of World Happiness Report

**Observers:** @frasercarter, Tag anyone who should be aware of this task.

**Detail:**
Email WHR and contact members directly/linkedin

**Sub-Tasks:**
Email following contacts
- [x] info@worldhappiness.report
- [ ] John F. Helliwell
- [ ] Richard Layard
- [ ] Jeffrey D. Sachs
- [ ] Jan-Emmanuel De Neve
- [ ] Lara B. Aknin
- [ ] Shun Wang

Foundations
- [ ] Fondazione Ernesto Illy, 
- [ ] illycaffè, 
- [ ] Davines Group, 
- [ ] The Blue Chip Foundation, 
- [ ] The William, 
- [ ] Jeff, and Jennifer Gross Family Foundation, 
- [ ] The Happier Way Foundation, 
- [ ] The Regeneration Society Foundation.
